name: C_test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make
      run: make
    - name: make lib
      run: make lib
    - name: run_python
      run: python3 main.py
